apiVersion: v1
kind: ConfigMap
metadata:
  name: service-urls
  namespace: healthcare
data:
  AUTH_SERVICE_URL: "http://auth-service:3001"
  PATIENT_SERVICE_URL: "http://patient-service:3002"
  DOCTOR_SERVICE_URL: "http://doctor-service:3003"
  APPOINTMENT_SERVICE_URL: "http://appointment-service:3004"
  TELEMEDICINE_SERVICE_URL: "http://telemedicine-service:3005"
  PAYMENT_SERVICE_URL: "http://payment-service:3006"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3007"
  AI_SERVICE_URL: "http://ai-symptom-service:3008"
  ML_SERVICE_URL: "http://ml-service:5000"
  KAFKA_BROKER: "kafka:9092"
  JITSI_BASE_URL: "https://meet.jit.si"
  NODE_ENV: "production"
  ENABLE_SMS: "true"
  FLASK_ENV: "production"
  FLASK_APP: "symptom_analyzer.py"
