apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  namespace: healthcare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.28
          command: ['sh', '-c', "until nc -z postgres-appointment 5432; do echo waiting for postgres-appointment; sleep 2; done"]
      containers:
        - name: appointment-service
          image: healthcare/appointment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3004
          env:
            - name: PORT
              value: "3004"
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: service-urls
                  key: NODE_ENV
            - name: DB_HOST
              value: postgres-appointment
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: appointment_db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt-secret
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-urls
                  key: AUTH_SERVICE_URL
            - name: DOCTOR_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-urls
                  key: DOCTOR_SERVICE_URL
            - name: TELEMEDICINE_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-urls
                  key: TELEMEDICINE_SERVICE_URL
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: service-urls
                  key: KAFKA_BROKER
          readinessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  namespace: healthcare
spec:
  selector:
    app: appointment-service
  ports:
    - port: 3004
      targetPort: 3004
